// Generated from shared/ttsGuide.ts. Edit that file, then run: node scripts/sync-shared.mjs

/**
 * The public TTS cheat sheet at /tts. It is data so the server can test that every example
 * really parses and does what its section claims. It is public: nothing here may mention how the
 * service is built, which providers it uses, its settings or its voice list.
 */

export interface GuideExample {
  /** Exactly what to type. */
  prompt: string;
  note?: string;
}

export interface GuideSection {
  id: string;
  title: string;
  intro: string;
  examples?: GuideExample[];
  /** Short tips shown as a list under the examples. */
  points?: string[];
  /** Words that all work, shown as small tags. */
  chips?: string[];
}

export const TTS_GUIDE_TITLE = "TTS cheat sheet";

export const TTS_GUIDE_LEAD =
  "Everything you can ask the text-to-speech for, with examples you can copy. Type your request after the channel's TTS command or reward.";

export const TTS_GUIDE_WARNING =
  "Results can be unstable or inaccurate at times: the AI may misread a request, a voice or effect may not sound the way you described it, and some requests fail outright. If something comes out wrong, try rephrasing it or making it simpler.";

export const TTS_GUIDE_FOOTER =
  "Voices and sounds are generated by AI, so the same request can sound a little different each time. Requests may have cooldowns, and TTS can be switched off at any time.";

export const TTS_GUIDE_SECTIONS: GuideSection[] = [
  {
    id: "basics",
    title: "The basics",
    intro:
      "Plain text is simply spoken. To direct a scene, put it in double parentheses. Words in quotes are spoken, and everything else describes who is talking, how, and where. With no quotes at all, it becomes a sound effect.",
    examples: [
      { prompt: "Welcome to the stream!", note: "Plain text is read out as it is." },
      {
        prompt: '((old woman says "Back in my day, we had no overlays"))',
        note: "Quoted words are spoken by whoever you describe.",
      },
      { prompt: "((thunder;4s))", note: "No quotes: a sound effect, four seconds long." },
      {
        prompt: 'This is a test. ((silence;1s)) ((man shouting: "NOW!")) ((lightning;3s))',
        note: "Up to ten parts in one request. They play in order, left to right.",
      },
    ],
  },
  {
    id: "characters",
    title: "Characters and voices",
    intro:
      "Describe who is talking: a gender, an age, a job or a creature. The closest matching voice is picked. Not every character has a voice of its own, so an unusual one may fall back to a more ordinary voice.",
    examples: [
      { prompt: '((angry pirate says "Arr, that be my parrot!"))' },
      { prompt: '((troll says "Me smash small overlay"))' },
      { prompt: '((witch says "Double, double, toil and trouble"))' },
      { prompt: '((young boy says "Can I have a snack?"))' },
      { prompt: '((wise wizard says "You shall not pass"))' },
    ],
    points: [
      "Pirates, trolls, demons, witches, old women and grandmas, wizards, kings, queens and villains tend to work best.",
      "Say a gender if it matters: a demon woman, an old man, a little girl.",
    ],
  },
  {
    id: "accents",
    title: "Accents",
    intro:
      "Put the accent in the character. It works best on expressive characters, and a very flat voice may only hint at it.",
    examples: [
      { prompt: '((sad French man says "I have lost my baguette"))' },
      { prompt: '((posh British woman says "How terribly rude"))' },
      { prompt: '((angry Scottish pirate says "Get off my ship"))' },
      { prompt: '((Texan cowboy says "Well howdy, partner"))' },
    ],
    chips: [
      "French",
      "British",
      "Scottish",
      "Welsh",
      "Irish",
      "Cockney",
      "Australian",
      "Southern American",
      "New York",
      "Canadian",
      "Russian",
      "German",
      "Italian",
      "Spanish",
      "Mexican",
      "Brazilian",
      "Indian",
      "Jamaican",
      "Swedish",
      "Norwegian",
      "Dutch",
      "Polish",
      "Greek",
      "Turkish",
      "Japanese",
      "Chinese",
      "South African",
      "Nigerian",
    ],
  },
  {
    id: "delivery",
    title: "How it is said",
    intro:
      "Say how the line is delivered. Shouting and screaming are only as convincing as the voice can manage, so a calm voice may sound like someone politely raising their voice.",
    examples: [
      { prompt: '((man whispers: "Do not tell chat"))' },
      { prompt: '((man yelling: "GET OFF MY LAWN"))' },
      { prompt: '((woman screaming in terror: "IT IS BEHIND YOU"))' },
      { prompt: '((girl crying: "I dropped my ice cream"))' },
      {
        prompt: '((man saying "Nooo" three times))',
        note: "Repeats the line, usually getting louder each time.",
      },
    ],
    points: [
      "Yell, shout, bellow and roar are read as a shout. Scream and shriek are read as a scream.",
      "Capital letters in the quotes make it feel louder.",
    ],
  },
  {
    id: "sounds",
    title: "Sound effects",
    intro:
      "Leave out the quotes and describe the sound itself. Describe the source, not the room or the length: those are added separately (see below).",
    examples: [
      { prompt: "((foxes screaming;5s))" },
      { prompt: "((glass breaking))" },
      { prompt: "((a crowd cheering;4s))" },
      { prompt: "((sword clash))" },
      {
        prompt: "((gigantic fart in a cathedral;5s))",
        note: "Gigantic, huge and enormous make a sound bigger and deeper.",
      },
    ],
  },
  {
    id: "places",
    title: "Places and echoes",
    intro: "Say where it happens and it sounds like it. This works on voices and on sound effects.",
    examples: [
      { prompt: "((thunder in a cave;6s))" },
      { prompt: '((man shouting in a cathedral: "HELLO"))' },
      { prompt: '((man talking down a well: "Is anybody up there?"))' },
      { prompt: "((huge explosion with echo;5s))" },
      { prompt: '((woman whispers from far away: "Can you hear me?"))' },
      {
        prompt: '((man yells from behind a door: "OPEN UP"))',
        note: "Also: through a wall, from outside, from another room, muffled.",
      },
    ],
    points: [
      "In a cave, in a church or cathedral, indoors, down a well, with echo, with reverb.",
      "Far away or distant makes it sound farther off.",
    ],
  },
  {
    id: "devices",
    title: "Through a device",
    intro: "Make a voice or sound come out of something.",
    examples: [
      { prompt: '((man over a walkie-talkie says "Come in, base"))' },
      { prompt: '((woman through an intercom says "Attention, all staff"))' },
      { prompt: '((man through a tin can says "Can you hear me?"))' },
      { prompt: '((announcer on an old radio says "This just in"))' },
      { prompt: "((gunshot over a walkie-talkie;3s))" },
    ],
    points: [
      "Walkie-talkie, intercom, megaphone, telephone, tin can (or string phone), old radio (or vintage radio).",
    ],
  },
  {
    id: "silly",
    title: "Silly voice effects",
    intro:
      "Add one of these to any voice or sound. You can pick one silly effect at a time, and combine it with a place or a device.",
    examples: [
      { prompt: '((chipmunk voice says "Where did everybody go?"))' },
      { prompt: '((slow motion voice says "Nooooo"))' },
      { prompt: '((robot voice says "Systems online"))' },
      { prompt: '((voice played backwards says "Welcome to the stream"))' },
      { prompt: '((underwater voice says "Can anybody hear me?"))' },
      {
        prompt: '((underwater man says "Help me" in a cave))',
        note: "An effect plus a place.",
      },
    ],
    points: [
      "Chipmunk (or helium), slow motion, robot (or vocoder), backwards (or reversed), underwater.",
      "Chipmunk and slow motion change the pitch as well as the speed, like a tape at the wrong speed.",
    ],
  },
  {
    id: "timing",
    title: "Speed and timing",
    intro:
      "End a scene with a length like ;6s for its total time (half a second to thirty seconds). Change the speed with speed= from half speed to double speed. The pitch stays the same.",
    examples: [
      { prompt: '((pirate says "Wait for me";speed=0.5x))', note: "Half speed." },
      { prompt: '((announcer says "Final round";speed=1.5x))' },
      { prompt: '((man says "I am in a hurry";speed=2x))', note: "Double speed." },
      { prompt: "((rumbling thunder;speed=0.5x;6s))", note: "Speed works on sound effects too." },
      { prompt: "((silence;2s))", note: "A pause of two seconds." },
    ],
    points: [
      "For a spoken line, words work as well: slowly, very quickly, half speed, double speed.",
      "For a sound effect, write speed= so it is not mistaken for part of the sound.",
    ],
  },
  {
    id: "tips",
    title: "Tips",
    intro: "A few things that help a request come out the way you meant it.",
    points: [
      "Only the words in quotes are spoken. Put effect words like underwater or in a cave outside the quotes, or they will be read out loud.",
      "Keep each part to one idea. Several short parts work better than one long, tangled one.",
      "A request can have at most ten parts and about six thousand characters.",
      "Names and unusual words may be pronounced oddly. Spelling one the way it sounds can help.",
      "If a request fails or sounds wrong, try again with simpler wording.",
    ],
  },
];
